version: "3.8"
services:
  redis:
    image: redis
  
  mongo:
      image: mongo

  app:
    build: .
    env_file:
      - .env
    ports:
      - "5111:5111"
    environment:
      - MONGO_URI=mongodb://mongo:27017/axion
      - REDIS_URI=redis://redis:6379
      - LONG_TOKEN_SECRET=${LONG_TOKEN_SECRET}
      - SHORT_TOKEN_SECRET=${SHORT_TOKEN_SECRET}
      - NACL_SECRET=${NACL_SECRET}
      - SUPER_ADMIN_INITIAL_PASSWORD=${SUPER_ADMIN_INITIAL_PASSWORD}
    depends_on:
      - mongo
      - redis